name: docker-build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: scripts/install_docker.sh && scripts/install_dependencies.sh

    - name: Build
      run: ./build_docker.sh

    - name: Launch
      run: ./launch_docker.sh
